name: wheel_inspector
description: A single-screen wheel inspection app using TFLite model detection.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # ML & Image Processing
  tflite_flutter: ^0.11.0
  image: ^4.1.7

  # Camera
  camera: ^0.11.0+2

  # File system
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/wheel_efficientnet.tflite
    - assets/wheel_efficientnet_AUG.tflite
    - assets/wheel_efficientnet_CROP.tflite
    - assets/labels.txt
