org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=false

# Java 17 configuration
# Use forward slashes or escaped backslashes for Windows paths
org.gradle.java.home=C:/Users/50014665/jdk-17.0.17+10
